(()=>{
  'use strict';
  const APP_VERSION='0.30.0';
  const GAS_URL='https://script.google.com/macros/s/AKfycbxNQYC7-aBE23cliuD1Zdze18xHh-q45P1qpBgwCCg0dYgxd1b8A-R63eGjzMtgOxMT/exec';
  const sidebar=document.querySelector('#sidebar'),backdrop=document.querySelector('#backdrop');
  const views=[...document.querySelectorAll('.view')],nav=[...document.querySelectorAll('.nav-btn')];
  const mobileTitle=document.querySelector('#mobileTitle'),characterCategory=document.querySelector('#characterCategory'),characterToggle=document.querySelector('#characterCategoryToggle');
  const characterNavList=document.querySelector('#characterNavList'),characterViewName=document.querySelector('#characterViewName');
  const frames={character:document.querySelector('#characterFrame'),facility:document.querySelector('#facilityFrame')};
  let characters=[],selectedCharacterId='',swRegistration=null,waitingWorker=null;
  const moduleState={character:{ready:false,lastCharacterId:''},facility:{ready:false}};

  const THEME_STORAGE_KEY='ra-app-theme-color';
  const THEMES={
    red:{label:"レッド",bg:"#eadfdd",paper:"#fff8f5",paper2:"#f3e3de",ink:"#352426",muted:"#786164",line:"#d8b5ae",accent:"#9d4149",accent2:"#c79650",deep:"#341e26",active:"#7a323b",hover:"#57272f",theme:"#7a323b",soft:"#edcec6",secondary:"#536a7d",secondaryText:"#ffffff",input:"#fffdf9",topbar:"#f8ece7",highlight:"#f1d3a4"},
    blue:{label:"ブルー",bg:"#dfe8f0",paper:"#f8fbff",paper2:"#e7eff6",ink:"#213041",muted:"#607184",line:"#b9cadb",accent:"#396d9f",accent2:"#b78350",deep:"#1c3047",active:"#315d87",hover:"#274a6b",theme:"#315d87",soft:"#d3e2ef",secondary:"#4d8089",secondaryText:"#ffffff",input:"#fcfeff",topbar:"#eaf2f8",highlight:"#ead5bd"},
    green:{label:"グリーン",bg:"#e3ebe1",paper:"#fbfcf7",paper2:"#e8efe3",ink:"#25342a",muted:"#647267",line:"#becdb8",accent:"#497253",accent2:"#b08a48",deep:"#21372a",active:"#3d6247",hover:"#304d38",theme:"#3d6247",soft:"#d5e3ce",secondary:"#6b778d",secondaryText:"#ffffff",input:"#fdfef9",topbar:"#edf3e9",highlight:"#e4d4ad"},
    purple:{label:"パープル",bg:"#e8e2ee",paper:"#fdf9ff",paper2:"#eee6f2",ink:"#31283a",muted:"#70647a",line:"#c9b8d3",accent:"#72528a",accent2:"#b97886",deep:"#32243e",active:"#604470",hover:"#493555",theme:"#604470",soft:"#dfd2e5",secondary:"#8a7549",secondaryText:"#ffffff",input:"#fffcff",topbar:"#f1eaf5",highlight:"#e8c8cf"},
    orange:{label:"オレンジ",bg:"#eee3d9",paper:"#fff9f3",paper2:"#f4e6d8",ink:"#39291f",muted:"#79695d",line:"#d7bfa8",accent:"#b76531",accent2:"#3e8082",deep:"#43291b",active:"#8e522b",hover:"#6a3e24",theme:"#8e522b",soft:"#edd4bc",secondary:"#3f7b80",secondaryText:"#ffffff",input:"#fffdf9",topbar:"#f7ebe0",highlight:"#cce0dd"},
    yellow:{label:"イエロー",bg:"#ebe6d2",paper:"#fffdf3",paper2:"#f3ebcd",ink:"#373121",muted:"#746d58",line:"#d5c58e",accent:"#98791f",accent2:"#4b6784",deep:"#37321f",active:"#755f1d",hover:"#58491c",theme:"#755f1d",soft:"#e9dda9",secondary:"#4b6784",secondaryText:"#ffffff",input:"#fffef8",topbar:"#f5efda",highlight:"#d6dfed"},
    pink:{label:"ピンク",bg:"#eee1e8",paper:"#fff9fc",paper2:"#f3e5ec",ink:"#39272f",muted:"#79646f",line:"#d5b7c5",accent:"#a95177",accent2:"#737ea4",deep:"#432736",active:"#86405e",hover:"#633047",theme:"#86405e",soft:"#ebceda",secondary:"#6f7899",secondaryText:"#ffffff",input:"#fffdfd",topbar:"#f7eaf0",highlight:"#dce1ef"},
    cyan:{label:"シアン",bg:"#dcebed",paper:"#f7fdfe",paper2:"#e3f0f1",ink:"#213538",muted:"#607579",line:"#b4d0d2",accent:"#37838a",accent2:"#7767a0",deep:"#17383d",active:"#2e6c72",hover:"#24545a",theme:"#2e6c72",soft:"#cee5e7",secondary:"#6c6093",secondaryText:"#ffffff",input:"#fbffff",topbar:"#e7f3f4",highlight:"#ded8ed"},
    navy:{label:"ネイビー",bg:"#dde2e9",paper:"#f8fafc",paper2:"#e6ebf1",ink:"#222d3b",muted:"#626d7c",line:"#bac2ce",accent:"#405a80",accent2:"#b28a50",deep:"#172339",active:"#334a6e",hover:"#283a55",theme:"#334a6e",soft:"#d2dae6",secondary:"#677487",secondaryText:"#ffffff",input:"#fcfdff",topbar:"#e9edf3",highlight:"#eadcc1"},
    brown:{label:"ブラウン",bg:"#eee6da",paper:"#fff9ef",paper2:"#f4ead7",ink:"#34251d",muted:"#74665c",line:"#d8c5a8",accent:"#8c542f",accent2:"#597872",deep:"#2f231d",active:"#5b3c2a",hover:"#493128",theme:"#6c432f",soft:"#e8d5b8",secondary:"#5a7770",secondaryText:"#ffffff",input:"#fffdf8",topbar:"#f6eddf",highlight:"#d4e0da"}
  };
  const LEGACY_THEME_KEYS={classic:'brown',violet:'purple',amber:'orange'};
  function currentTheme(){
    let key=localStorage.getItem(THEME_STORAGE_KEY)||'brown';
    if(LEGACY_THEME_KEYS[key]){key=LEGACY_THEME_KEYS[key];try{localStorage.setItem(THEME_STORAGE_KEY,key)}catch(_){}}
    return THEMES[key]?key:'brown';
  }
  function themePairs(theme){return {
    '--bg':theme.bg,'--paper':theme.paper,'--paper2':theme.paper2,'--ink':theme.ink,'--muted':theme.muted,'--line':theme.line,
    '--accent':theme.accent,'--accent2':theme.accent2,'--app-deep':theme.deep,'--app-active':theme.active,'--app-hover':theme.hover,'--theme-soft':theme.soft,
    '--theme-secondary':theme.secondary,'--theme-secondary-text':theme.secondaryText,'--theme-input':theme.input,'--theme-topbar':theme.topbar,'--theme-highlight':theme.highlight,
    '--ra-desk':theme.deep,'--ra-desk-2':theme.hover,'--ra-page':theme.paper,'--ra-page-2':theme.paper2,'--ra-page-3':theme.soft,
    '--ra-ink':theme.ink,'--ra-muted':theme.muted,'--ra-line':theme.line,'--ra-line-soft':theme.line,'--ra-line-dark':theme.hover,
    '--ra-navy':theme.accent,'--ra-navy-2':theme.deep,'--ra-burgundy':theme.accent,'--ra-burgundy-2':theme.deep,
    '--ra-brass':theme.accent2,'--ra-brass-light':theme.highlight
  }}
  function applyThemeToFrame(frame,theme,key=currentTheme()){
    try{
      const doc=frame?.contentDocument;if(!doc)return;
      const root=doc.documentElement,body=doc.body;root.dataset.raTheme=key;if(body)body.dataset.raTheme=key;
      Object.entries(themePairs(theme)).forEach(([k,v])=>{root.style.setProperty(k,v);body?.style.setProperty(k,v)});
      let style=doc.getElementById('raAppFullThemeV025');
      if(!style){style=doc.createElement('style');style.id='raAppFullThemeV025';doc.head?.appendChild(style)}
      style.textContent=`
        html,body{background:var(--bg)!important;color:var(--ink)!important}
        body.ra-app{color:var(--ink)!important;background:linear-gradient(145deg,var(--bg),color-mix(in srgb,var(--bg) 74%,var(--app-deep) 26%))!important}
        body.ra-app>header,body.ra-app header{background:color-mix(in srgb,var(--theme-topbar) 94%,transparent)!important;border-color:var(--line)!important;color:var(--ink)!important}
        body.ra-app>main{background:var(--paper)!important;border-color:var(--line)!important;color:var(--ink)!important}
        body.ra-app :is(.panel,.big-section,.card,.mini-card,.status-box,.resource-card,.choice-card,.help-card,.compact-storage-panel,.facility-work-block,.facility-summary,.autosave-panel,.dialog-inner,.weapon-modal-dialog,.branch-controls,.branch-graph-scroll,.catalog-rank-controls,.inventory-filter-panel,.inventory-search-panel,.tab-block,.subnav-block,.progress-fold,.community-manager-card,.weather-manager,.day-stat,.event-card,.result,.drop-row,.monster-combobox-menu,.facility-product,.facility-card,.record-list-search,.admin-global-search-panel,.admin-global-search-card,.table-pagination){border-color:var(--line)!important;background:var(--paper)!important;color:var(--ink)!important;box-shadow:0 8px 22px color-mix(in srgb,var(--app-deep) 10%,transparent)!important}
        body.ra-app :is(.tab-nav,.tabs,.subtabs,.buttons,.quest-tools,.quest-category-bar,.toolbar,.section-actions,.filter-actions,.facility-actions,.help-actions,.monster-output-actions,.modal-foot,.facility-inner-tabs,.facility-weapon-category-tabs){background:var(--paper2)!important;border-color:var(--line)!important;color:var(--ink)!important}
        body.ra-app :is(input,select,textarea){background:var(--theme-input)!important;color:var(--ink)!important;border-color:var(--line)!important;box-shadow:inset 0 1px 2px color-mix(in srgb,var(--app-deep) 8%,transparent)!important}
        body.ra-app :is(input,select,textarea):focus{border-color:var(--accent)!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--accent) 22%,transparent)!important}
        body.ra-app button:not(.ghost):not(.danger):not(.secondary),body.ra-app :is(.tab,.subtab,.tab-btn,.editor-tab-btn,.quest-category-btn,.facility-inner-tab,.facility-weapon-category-tab).active{background:linear-gradient(180deg,color-mix(in srgb,var(--accent) 82%,#fff 18%),var(--accent))!important;border-color:color-mix(in srgb,var(--accent) 78%,var(--app-deep) 22%)!important;color:#fff!important;box-shadow:0 2px 0 color-mix(in srgb,var(--accent) 62%,#000 38%),0 5px 12px color-mix(in srgb,var(--accent) 22%,transparent)!important;text-shadow:0 1px 0 rgba(0,0,0,.18)!important}
        body.ra-app button.secondary,body.ra-app :is(.tab,.subtab,.tab-btn,.editor-tab-btn,.quest-category-btn,.facility-inner-tab,.facility-weapon-category-tab):not(.active){background:linear-gradient(180deg,color-mix(in srgb,var(--theme-secondary) 82%,#fff 18%),var(--theme-secondary))!important;border-color:color-mix(in srgb,var(--theme-secondary) 76%,var(--app-deep) 24%)!important;color:var(--theme-secondary-text)!important;box-shadow:0 2px 0 color-mix(in srgb,var(--theme-secondary) 62%,#000 38%),0 4px 10px color-mix(in srgb,var(--theme-secondary) 18%,transparent)!important;text-shadow:0 1px 0 rgba(0,0,0,.16)!important}
        body.ra-app button.ghost{background:var(--paper)!important;border-color:var(--accent)!important;color:var(--accent)!important;box-shadow:none!important;text-shadow:none!important}
        body.ra-app button.danger{background:linear-gradient(180deg,#b45656,#8e3333)!important;border-color:#6b2727!important;color:#fff!important}
        body.ra-app :is(.badge,.pill,.quest-pill){background:var(--paper2)!important;border-color:var(--line)!important;color:var(--muted)!important}
        body.ra-app :is(.progress-fold>summary,.ra-progress-load-fold>summary,.ra-admin-fold>summary){background:color-mix(in srgb,var(--paper2) 82%,var(--theme-highlight) 18%)!important;color:var(--ink)!important;border-color:var(--line)!important}
        body.ra-app :is(.progress-wrap,.community-manager-progress){background:color-mix(in srgb,var(--paper2) 80%,var(--line) 20%)!important;border-color:var(--line)!important}
        body.ra-app :is(.progress-bar,.community-manager-progress span){background:linear-gradient(90deg,var(--accent),var(--accent2))!important}
        body.ra-app :is(.section-title,.big-section>h2,.panel>h2,.panel>h3,.summary-line h2,h1,h2,h3){color:var(--ink)!important;border-color:color-mix(in srgb,var(--line) 78%,var(--accent2) 22%)!important}
        body.ra-app :is(.muted,.hint,.subtitle,.version,.small,.notice){color:var(--muted)!important}
        body.ra-app .ra-build-info,body.ra-app .build{background:var(--paper2)!important;border-color:var(--line)!important;color:var(--ink)!important}
        body.ra-app .tab-nav#progressTabNav{background:color-mix(in srgb,var(--paper2) 92%,var(--theme-highlight) 8%)!important;border-color:var(--line)!important}
        body.ra-app .status.good,body.ra-app .event-card.random{background:color-mix(in srgb,var(--paper) 82%,#bfe2c9 18%)!important}
        body.ra-app .status.bad{background:color-mix(in srgb,var(--paper) 84%,#e8b8b3 16%)!important}
        body.ra-app .status.warn,body.ra-app .event-card.fixed{background:color-mix(in srgb,var(--paper) 82%,var(--theme-highlight) 18%)!important}
      `;
    }catch(_){ }
  }
  function applyTheme(key,{persist=true}={}){
    key=LEGACY_THEME_KEYS[key]||key;const theme=THEMES[key]||THEMES.brown;key=THEMES[key]?key:'brown';
    if(persist)localStorage.setItem(THEME_STORAGE_KEY,key);
    const root=document.documentElement;root.dataset.raTheme=key;document.body?.setAttribute('data-ra-theme',key);
    Object.entries(themePairs(theme)).forEach(([k,v])=>root.style.setProperty(k,v));
    document.querySelector('meta[name="theme-color"]')?.setAttribute('content',theme.theme);
    const select=document.querySelector('#themeColorSelect');if(select&&select.value!==key)select.value=key;
    Object.values(frames||{}).forEach(frame=>applyThemeToFrame(frame,theme,key));
  }

  function readBinding(){const role=sessionStorage.getItem('ra-proto-role')||'player';const loginKey=String(sessionStorage.getItem('ra-proto-login-player-key')||'').trim();const accountKey=loginKey?`ra-proto-bind-account-${encodeURIComponent(loginKey)}`:'';const raw=(accountKey?localStorage.getItem(accountKey):'')||localStorage.getItem('ra-proto-bind-'+role)||localStorage.getItem('ra-proto-bind-player')||'';try{return raw?JSON.parse(raw):{};}catch(_){return{}}}
  const binding=readBinding();window.RA_PLAYER_CONTEXT={charKey:String(binding.charKey||'').trim(),facilityKey:String(binding.facilityKey||'').trim(),characterId:''};
  function closeDrawer(){sidebar.classList.remove('open');backdrop.classList.remove('show')}
  function characterButtons(){return [...document.querySelectorAll('.character-nav-btn')]}
  const frameTimers=new Map();
  function setFrameLoading(name,text='読み込み中'){
    const frame=frames[name],wrap=frame?.closest('.module-frame-wrap');if(!wrap)return;if(moduleState[name])moduleState[name].ready=false;wrap.classList.remove('loaded','load-error');
    const label=wrap.querySelector('.frame-loading-text');if(label)label.textContent=text||'読み込み中';clearTimeout(frameTimers.get(name));
    const timeout=name==='character'?120000:45000;
    frameTimers.set(name,setTimeout(()=>{if(wrap.classList.contains('loaded'))return;if(name==='character'){if(label)label.textContent='通信を再試行しています…';return;}wrap.classList.add('load-error');if(label)label.textContent='読み込みがタイムアウトしました。再読み込みできます。';},timeout));
  }
  function setFrameReady(name){const frame=frames[name],wrap=frame?.closest('.module-frame-wrap');if(!wrap)return;if(moduleState[name])moduleState[name].ready=true;clearTimeout(frameTimers.get(name));frameTimers.delete(name);wrap.classList.remove('load-error');wrap.classList.add('loaded');applyThemeToFrame(frame,THEMES[currentTheme()]);}
  function setFrameError(name,text='読み込みに失敗しました'){const frame=frames[name],wrap=frame?.closest('.module-frame-wrap');if(!wrap)return;clearTimeout(frameTimers.get(name));frameTimers.delete(name);wrap.classList.remove('loaded');wrap.classList.add('load-error');const label=wrap.querySelector('.frame-loading-text');if(label)label.textContent=text;}
  function reloadFrame(name){const frame=frames[name];if(!frame)return;const base=frame.dataset.src||frame.getAttribute('src')||'';if(!base)return;frame.dataset.loaded='1';if(moduleState[name])moduleState[name].ready=false;if(name==='character')moduleState.character.lastCharacterId='';setFrameLoading(name,'再読み込み中');try{const u=new URL(base,location.href);u.searchParams.set('retry',String(Date.now()));frame.src=u.toString();}catch(_){frame.src=base+(base.includes('?')?'&':'?')+'retry='+Date.now();}}
  function ensureFrame(name){const frame=frames[name];if(!frame||frame.dataset.loaded==='1')return;frame.dataset.loaded='1';setFrameLoading(name);frame.addEventListener('load',()=>{applyThemeToFrame(frame,THEMES[currentTheme()]);const wrap=frame.closest('.module-frame-wrap');if(!wrap?.classList.contains('loaded')){const label=wrap?.querySelector('.frame-loading-text');if(label)label.textContent='データを読み込み中';}});frame.src=frame.dataset.src;}
  function show(name,{writeHash=true}={}){if(!document.querySelector('#view-'+name))name='home';views.forEach(v=>v.classList.toggle('active',v.id==='view-'+name));nav.forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name!=='character')characterButtons().forEach(b=>b.classList.remove('active'));const active=document.querySelector('#view-'+name);mobileTitle.textContent=active?.dataset.title||'Recraft Alchemia';ensureFrame(name);closeDrawer();if(writeHash&&location.hash!=='#'+name)history.pushState(null,'','#'+name);}
  function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
  function jsonpOnce(action,payload={},timeoutMs=24000){return new Promise((resolve,reject)=>{const cb='raPlayerProtoCb_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script');const timer=setTimeout(()=>{cleanup();reject(new Error('キャラクター一覧の取得に時間がかかっています。'));},timeoutMs);function cleanup(){clearTimeout(timer);try{delete window[cb]}catch(_){window[cb]=undefined}script.remove()}window[cb]=json=>{cleanup();if(!json||json.ok===false)reject(new Error(json?.error||'キャラクター一覧を取得できませんでした。'));else resolve(json)};try{const u=new URL(GAS_URL);u.searchParams.set('api','1');u.searchParams.set('action',action);u.searchParams.set('callback',cb);u.searchParams.set('_t',Date.now());Object.entries(payload).forEach(([k,v])=>{if(v!==undefined&&v!==null)u.searchParams.set(k,typeof v==='object'?JSON.stringify(v):String(v))});script.onerror=()=>{cleanup();reject(new Error('キャラクター一覧の通信に失敗しました。'));};script.src=u.toString();document.head.appendChild(script);}catch(e){cleanup();reject(e)}})}
  async function jsonp(action,payload={}){let last;for(let i=0;i<3;i++){try{return await jsonpOnce(action,payload,24000+i*6000)}catch(e){last=e;if(i<2)await sleep([700,1800][i])}}throw last||new Error('キャラクター一覧を取得できませんでした。')}
  function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function listCacheKey(){return 'ra-char-list-cache:'+window.RA_PLAYER_CONTEXT.charKey}
  function readListCache(){try{const v=JSON.parse(sessionStorage.getItem(listCacheKey())||'null');return Array.isArray(v?.items)?v.items:null}catch(_){return null}}
  function saveListCache(items){try{sessionStorage.setItem(listCacheKey(),JSON.stringify({at:Date.now(),items}))}catch(_){}}
  function renderCharacterNav(){if(!characterNavList)return;if(!characters.length){characterNavList.innerHTML='<div class="character-nav-status empty">保存済みキャラクターはありません。</div>';return;}characterNavList.innerHTML=characters.map(c=>`<button class="character-nav-btn" type="button" data-character-id="${escapeHtml(c.id)}">${escapeHtml(c.name||'無名のキャラクター')}</button>`).join('');characterButtons().forEach(btn=>btn.addEventListener('click',()=>selectCharacterById(btn.dataset.characterId)));}
  async function loadCharacterList({background=false}={}){const key=window.RA_PLAYER_CONTEXT.charKey;if(!key){characterNavList.innerHTML='<div class="character-nav-status error">ログイン時のキャラクターシート用プレイヤーキー紐づけが見つかりません。</div>';return;}const cached=readListCache();if(cached&&!characters.length){characters=cached;renderCharacterNav();}if(!background&&!characters.length)characterNavList.innerHTML='<div class="character-nav-status loading"><span class="mini-spinner" aria-hidden="true"></span><span>読み込み中</span></div>';try{const res=await jsonp('list',{playerKey:key});characters=Array.isArray(res)?res:(Array.isArray(res.items)?res.items:(Array.isArray(res.data?.items)?res.data.items:[]));saveListCache(characters);renderCharacterNav();routeFromHash();}catch(e){if(characters.length)return;characterNavList.innerHTML=`<div class="character-nav-status error"><div>${escapeHtml(e.message)}</div><button class="character-nav-retry" type="button">一覧を再読み込み</button></div>`;characterNavList.querySelector('.character-nav-retry')?.addEventListener('click',()=>loadCharacterList());}}
  function postCharacter(message){try{frames.character?.contentWindow?.postMessage(message,location.origin)}catch(_){}}
  function selectCharacterById(id,{writeHash=true}={}){const character=characters.find(c=>String(c.id)===String(id));if(!character)return;const nextId=String(character.id),sameCharacter=selectedCharacterId===nextId;selectedCharacterId=nextId;window.RA_PLAYER_CONTEXT.characterId=selectedCharacterId;characterButtons().forEach(b=>b.classList.toggle('active',String(b.dataset.characterId)===selectedCharacterId));characterViewName.textContent=character.name||'無名のキャラクター';show('character',{writeHash:false});mobileTitle.textContent=character.name||'キャラクター';ensureFrame('character');if(!sameCharacter||moduleState.character.lastCharacterId!==selectedCharacterId){moduleState.character.lastCharacterId=selectedCharacterId;postCharacter({type:'RA_OPEN_CHARACTER',characterId:selectedCharacterId,force:false});}if(writeHash)history.pushState(null,'','#character/'+encodeURIComponent(selectedCharacterId));}
  function openNewCharacter({writeHash=true}={}){selectedCharacterId='';window.RA_PLAYER_CONTEXT.characterId='__new__';characterButtons().forEach(b=>b.classList.remove('active'));characterViewName.textContent='新規キャラクター';show('character',{writeHash:false});mobileTitle.textContent='新規キャラクター';ensureFrame('character');moduleState.character.lastCharacterId='';postCharacter({type:'RA_NEW_CHARACTER'});if(writeHash&&location.hash!=='#character/new')history.pushState(null,'','#character/new');}
  window.addEventListener('message',ev=>{if(ev.origin!==location.origin)return;const name=Object.entries(frames).find(([,frame])=>frame?.contentWindow===ev.source)?.[0];if(!name)return;const type=String(ev.data?.type||'');if(type==='RA_MODULE_LOADING')setFrameLoading(name,String(ev.data?.text||'読み込み中'));else if(type==='RA_MODULE_READY'){setFrameReady(name);if(name==='character'&&window.RA_PLAYER_CONTEXT.characterId&&!String(window.RA_PLAYER_CONTEXT.characterId).startsWith('__'))moduleState.character.lastCharacterId=String(window.RA_PLAYER_CONTEXT.characterId);}else if(type==='RA_MODULE_ERROR')setFrameError(name,String(ev.data?.text||'読み込みに失敗しました'));else if(type==='RA_CHARACTER_LIST_CHANGED')loadCharacterList({background:true});});
  characterToggle?.addEventListener('click',()=>{const open=characterCategory.classList.toggle('open');characterToggle.setAttribute('aria-expanded',String(open));});document.querySelector('#menuBtn').onclick=()=>{sidebar.classList.toggle('open');backdrop.classList.toggle('show')};backdrop.onclick=closeDrawer;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>show(b.dataset.view));document.querySelectorAll('[data-open-view]').forEach(b=>b.onclick=()=>show(b.dataset.openView));document.querySelectorAll('[data-retry-frame]').forEach(button=>button.addEventListener('click',()=>reloadFrame(button.dataset.retryFrame)));document.querySelector('#newCharacterNavBtn')?.addEventListener('click',()=>openNewCharacter());
  document.querySelectorAll('[data-player-maintenance]').forEach(button=>button.addEventListener('click',()=>{const action=button.dataset.playerMaintenance;if(action==='character-db'||action==='initial-stock'){ensureFrame('character');postCharacter({type:action==='character-db'?'RA_RELOAD_CHARACTER_DB':'RA_SYNC_INITIAL_WAREHOUSE'});}else if(action==='facility-db'){ensureFrame('facility');try{frames.facility?.contentWindow?.postMessage({type:'RA_RELOAD_FACILITY_DB'},location.origin)}catch(_){}}}));
  document.querySelector('#themeColorSelect')?.addEventListener('change',e=>applyTheme(e.currentTarget.value));applyTheme(currentTheme(),{persist:false});
  function routeFromHash(){const raw=(location.hash||'#home').slice(1);if(raw==='character/new')return openNewCharacter({writeHash:false});if(raw.startsWith('character/')){const id=decodeURIComponent(raw.slice('character/'.length));if(characters.length&&characters.some(c=>String(c.id)===id))return selectCharacterById(id,{writeHash:false});return;}show(raw,{writeHash:false});}
  addEventListener('popstate',routeFromHash);
  const notice=document.querySelector('#updateNotice'),noticeText=notice?.querySelector('span');
  async function checkPublishedVersion(){try{const res=await fetch('./version.json?t='+Date.now(),{cache:'no-store'});if(!res.ok)return;const data=await res.json(),published=String(data.version||'');if(published&&published!==APP_VERSION){if(noticeText)noticeText.textContent=`Playerアプリの新しいバージョン ${published} があります（現在 ${APP_VERSION}）。`;notice.hidden=false;await swRegistration?.update().catch(()=>{});}}catch(_){}}
  async function applyUpdate(){try{if(swRegistration){await swRegistration.update();if(swRegistration.waiting){swRegistration.waiting.postMessage({type:'SKIP_WAITING'});return;}const worker=swRegistration.installing;if(worker){worker.addEventListener('statechange',()=>{if(worker.state==='installed')(swRegistration.waiting||worker).postMessage({type:'SKIP_WAITING'});});return;}}}catch(_){}location.reload();}
  document.querySelector('#applyUpdate').onclick=applyUpdate;document.querySelector('#dismissUpdate').onclick=()=>{notice.hidden=true};
  if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').then(reg=>{swRegistration=reg;if(reg.waiting&&navigator.serviceWorker.controller){waitingWorker=reg.waiting;notice.hidden=false;}reg.addEventListener('updatefound',()=>{const worker=reg.installing;if(!worker)return;worker.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){waitingWorker=reg.waiting||worker;notice.hidden=false;}});});reg.update().catch(()=>{});}).catch(()=>{});let reloading=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(reloading)return;reloading=true;location.reload()});}
  addEventListener('focus',checkPublishedVersion);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkPublishedVersion()});setInterval(checkPublishedVersion,5*60*1000);
  routeFromHash();loadCharacterList();checkPublishedVersion();
})();
