function renderCraftLists(){
  const area=$('craftListArea'),status=$('craftListStatus');if(!area)return;
  craftListsState=normalizeCraftLists(craftListsState);
  document.querySelectorAll('[data-craft-list-view]').forEach(btn=>btn.classList.toggle('active',btn.dataset.craftListView===craftListView));
  const entries=craftListView==='favorites'?craftListsState.favorites:craftListsState.goals;
  if(!entries.length){area.innerHTML=`<div class="craft-list-empty">${craftListView==='favorites'?'お気に入りはまだ登録されていません。':'作成目標はまだ登録されていません。'}</div>`;if(status){status.className='status-box';status.textContent='施設から登録できます。';}return;}
  if(status){status.className='status-box ok';status.textContent=`${entries.length}件を表示しています。素材所持数は現在値です。`;}
  area.innerHTML=entries.map((raw,index)=>{const e=craftResolvedEntry(raw),runs=craftListView==='goals'?Math.max(1,Number(e.targetRuns)||1):1,resultTotal=e.resultCount*runs,req=craftRequirementState(e,runs),maxRuns=craftMaxRuns(e,craftListView==='goals'?runs:999);if(craftListView==='favorites')return `<article class="craft-list-card"><div class="craft-list-card-head"><button type="button" class="craft-favorite-name" data-craft-favorite-open="${index}">${esc(e.resultName)}</button><button type="button" class="ghost" data-craft-favorite-remove="${index}">お気に入りから削除</button></div><div class="muted">クリックすると作成回数と必要素材を確認できます。</div></article>`;return `<article class="craft-list-card"><div class="craft-list-card-head"><div><h3>${esc(e.resultName)}</h3><div class="muted">残り ${runs}回 / ${resultTotal}個</div></div><button type="button" class="ghost" data-craft-goal-reduce="${index}">目標を減らす</button></div><div class="craft-material-list">${craftMaterialRowsHtml(req)}</div><div class="craft-list-actions"><label>今回の作成回数 <input type="number" min="1" max="${runs}" value="${Math.max(1,Math.min(runs,maxRuns||1))}" data-craft-goal-runs="${index}"></label><button type="button" data-craft-goal-make="${index}" ${maxRuns<1?'disabled':''}>作成する</button></div></article>`;}).join('');
  area.querySelectorAll('[data-craft-goal-runs]').forEach(input=>input.addEventListener('input',()=>{const index=Number(input.dataset.craftGoalRuns),entry=craftListsState.goals[index],runs=Math.max(1,Math.min(Number(entry?.targetRuns)||1,Math.floor(Number(input.value)||1))),btn=area.querySelector(`[data-craft-goal-make="${index}"]`);if(btn)btn.disabled=!craftCanMake(entry,runs);}));
}
function craftEquippedItemIds(){const ids=new Set();const eq=getEquipmentState();Object.values(eq||{}).forEach(row=>{const id=String(row?.itemId||'').trim();if(id)ids.add(id);});return ids;}
function craftConsumeMaterials(entry={},runs=1){const req=craftRequirementState(entry,runs);if(!req.length||req.some(x=>!x.met))throw new Error('必要素材が不足しています。');const equipped=craftEquippedItemIds(),willUseEquipped=[];for(const row of req){let nonEq=0;for(const raw of inventoryItemsState){if(String(raw?.name||'').trim()!==row.name)continue;const id=String(inventoryItemKey(normalizeInventoryItem(raw))||'').trim();if(!equipped.has(id))nonEq+=Math.max(0,Number(raw.count||0));}if(nonEq<row.need)willUseEquipped.push(`${row.name} ×${row.need-nonEq}`);}if(willUseEquipped.length&&!window.confirm(`装備中のアイテムを素材として使用します。\n${willUseEquipped.join('\n')}\n\n作成を続けますか？`))return false;for(const row of req){let remain=row.need;const order=[...inventoryItemsState.keys()].sort((a,b)=>{const ai=equipped.has(String(inventoryItemKey(normalizeInventoryItem(inventoryItemsState[a]))||'')),bi=equipped.has(String(inventoryItemKey(normalizeInventoryItem(inventoryItemsState[b]))||''));return Number(ai)-Number(bi);});for(const i of order){if(remain<=0)break;const raw=inventoryItemsState[i];if(!raw||String(raw.name||'').trim()!==row.name)continue;const have=Math.max(0,Number(raw.count||0));if(!have)continue;const take=Math.min(have,remain);inventoryItemsState[i]=normalizeInventoryItem({...raw,count:have-take});remain-=take;}}inventoryItemsState=inventoryItemsState.filter(raw=>Math.max(0,Number(raw.count||0))>0);invalidateInventoryDerivedCache();return true;}
function craftOutputPreset(entry={}){const ref=craftResolvedEntry(entry),name=String(ref.resultName||'').trim();const row=(Array.isArray(DB_INITIAL_ITEM_MASTER)?DB_INITIAL_ITEM_MASTER:[]).find(x=>String(x.name||'').trim()===name);if(row)return dbItemToInventoryItem(row);return normalizeInventoryItem({name,kind:ref.resultKind||'アイテム',category:ref.resultKind||'',count:1,location:'倉庫'});}
function craftAddOutput(entry={},runs=1){const ref=craftResolvedEntry(entry),amount=Math.max(1,ref.resultCount)*Math.max(1,Math.floor(Number(runs)||1)),preset=craftOutputPreset(ref),kind=normalizeInventoryKind(preset.kind||ref.resultKind||'アイテム');if(inventoryKindUsesIndividualRecord(kind)){for(let i=0;i<amount;i++)inventoryItemsState.push(normalizeInventoryItem({...preset,id:newInventoryInstanceId(),count:1,location:'倉庫'}));}else{let idx=inventoryItemsState.findIndex(raw=>String(raw?.name||'').trim()===String(preset.name||'').trim()&&normalizeInventoryKind(raw?.kind||'')===kind);if(idx>=0)inventoryItemsState[idx]=normalizeInventoryItem({...inventoryItemsState[idx],count:Math.max(0,Number(inventoryItemsState[idx].count||0))+amount});else inventoryItemsState.push(normalizeInventoryItem({...preset,count:amount,location:'倉庫'}));}invalidateInventoryDerivedCache();return amount;}
async function craftExecute(entry={},runs=1,{goalIndex=-1}={}){runs=Math.max(1,Math.floor(Number(runs)||1));if((!Array.isArray(DB_INITIAL_ITEM_MASTER)||!DB_INITIAL_ITEM_MASTER.length)&&typeof loadCharacterSheetMasterFromDbForInitial==='function'){try{await loadCharacterSheetMasterFromDbForInitial();}catch(_){}}if(!craftCanMake(entry,runs)){showToast('必要素材が不足しています。','error');return false;}if(!craftConsumeMaterials(entry,runs))return false;const amount=craftAddOutput(entry,runs);if(goalIndex>=0&&craftListsState.goals[goalIndex]){craftListsState.goals[goalIndex].targetRuns=Math.max(0,(Number(craftListsState.goals[goalIndex].targetRuns)||1)-runs);if(craftListsState.goals[goalIndex].targetRuns<=0)craftListsState.goals.splice(goalIndex,1);}markInventoryUiDirty();try{setEquipmentState(getEquipmentState());}catch(_){}renderCraftLists();updateSummary();autoSaveDraftSoon(['inventory','equipment','craftLists']);showToast(`${craftResolvedEntry(entry).resultName}を${amount}個作成し、倉庫へ登録しました。`,'ok');return true;}
function openCraftCreateDialog(index){const entry=craftListsState.favorites[index];if(!entry)return;craftDialogContext={type:'favorite',index};$('craftCreateDialogTitle').textContent=craftResolvedEntry(entry).resultName;$('craftCreateRuns').value='1';updateCraftCreateDialog();$('craftCreateDialog').showModal();}
function updateCraftCreateDialog(){if(!craftDialogContext)return;const entry=craftListsState.favorites[craftDialogContext.index];if(!entry)return;const runs=Math.max(1,Math.floor(Number($('craftCreateRuns').value)||1)),ref=craftResolvedEntry(entry),req=craftRequirementState(ref,runs);$('craftCreateResultSummary').textContent=`完成数：${ref.resultCount*runs}個`;$('craftCreateMaterials').innerHTML=craftMaterialRowsHtml(req);const can=req.length>0&&req.every(x=>x.met);$('craftCreateConfirmBtn').disabled=!can;$('craftCreateStatus').className=can?'status-box ok':'status-box warn';$('craftCreateStatus').textContent=can?'必要素材を満たしています。':'必要素材が不足しています。';}
